### ISSUE TITLE
Anything else to obey, did I miss/misinterprete something?

### ISSUE THREAD

**Issue by md-admin** [siilike/certbot-dns-standalone#20]
My current task is to get a wildcard certificate for "*.domain.tld" and I feel completely stuck.

I've set and propagated the _acme-challenge record:

# host _acme-challenge.domain.tld
Processing…
_acme-challenge.domain.tld is an alias for lnx40.domain.tld.
lnx40.domain.tld has address 194.#.##.92

On lnx40.domain.tld certbot-dns-standalone is run with:
  
certbot certonly  --dry-run -vvvv  --config /etc/letsencrypt/cli.ini  --preferred-challenges dns-01  --authenticator dns-standalone --dns-standalone-port=53 --dns-standalone-address=194.#.##.92 --doma

and always ends with:
…
Certbot failed to authenticate some domains (authenticator: dns-standalone). The Certificate Authority reported these problems:
  Domain: domain.tld
  Type:   unauthorized
  Detail: No TXT record found at _acme-challenge.domain.tld

  Domain: domain.tld
  Type:   unauthorized
  Detail: No TXT record found at _acme-challenge.domain.tld
…

It is verified that lnx40.domain.tld can rceive DNS queries from the internet. But Python and its messages are still a mystery for me. Any help is appreciated.

**Comment by md-admin** [comment]
That --doma above is in indeed '--domain "domain.tld,*.domain.tld"'.

**Comment by siilike** [comment]
You likely did not set up the NS part, so instead of certbot the reply comes from the nameserver of `domain.tld`.

I'll assume that you'll want to use `lnx40.domain.tld`, but it could also be `domain.tld` directly.

You should create a NS record for `acme.lnx40.domain.tld`, this means that `*.acme.lnx40.domain.tld` is managed by that nameserver (in this case it will be certbot):
```
acme.lnx40.domain.tld.     IN  NS  ns.acme.lnx40.domain.tld.
ns.acme.lnx40.domain.tld.  IN  A   194.#.##.92
```
The first line says that `*.acme.lnx40.domain.tld` should be managed by the nameserver `ns.acme.lnx40.domain.tld` and the second one says that `ns.acme.lnx40.domain.tld` is at `194.#.##.92` which is where certbot is run.

Then change `_acme-challenge.domain.tld` to be a CNAME record to `domain.tld.acme.lnx40.domain.tld`.

**Comment by md-admin** [comment]
Thank yo so much for the given details:

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-standalone, Installer None
Certificate not due for renewal, but simulating renewal for dry run
Simulating renewal of an existing certificate for domain.tld and *.domain.tld
Performing the following challenges:
dns-01 challenge for domain.tld
dns-01 challenge for domain.tld
Waiting 0 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges
Dry run: skipping deploy hook command: /etc/letsencrypt/renewal-hooks/deploy/notifyByMail
**The dry run was successful.**
