### ISSUE TITLE
Sorry couldn't find another way to contact

### ISSUE THREAD

**Issue by johnestep** [siilike/certbot-dns-standalone#6]
Is there a way to automate this?? Or does it have to be manually ran?

**Comment by siilike** [comment]
What do you mean by automating? If you want to programmatically set up certbot with the plugin, you need to run ``certbot --non-interactive --agree-tos --email certmaster@example.com certonly --preferred-challenges dns --authenticator certbot-dns-standalone:dns-standalone -d example.com`` where ``example.com`` is your domain name.

To automate certificate renewal just add ``certbot renew`` to crontab.

**Comment by johnestep** [comment]
Thank you you gave the example I was looking for!

However, if I try a dry-run it fails saying incorrect text record, but it actually matches the txt record, so something else must be happening I can't seem to figure out.

**Comment by johnestep** [comment]
So, the renew fails. I am guessing you are trying to change the DNS TXT record?

**Comment by siilike** [comment]
1. Check that nothing is running on port 53.
2. Check that the CNAME record is correct: `dig _acme-challenge.example.net txt` should show that it is a CNAME record that points to `example.net.acme.example.com` where `example.net` is the domain you want the certificate for and `acme.example.com` is the subdomain for certbot.
3. Test that the CNAME record is correct:
    * run `socat - udp4-listen:53,reuseaddr,fork,bind=1.2.3.4` where 1.2.3.4 is the IP address you use for certbot
    * run `dig _acme-challenge.example.net txt` and see if socat produces some garbage as output

**Comment by johnestep** [comment]
I thought the _acme-challenge record needed to be a text record?
Or are you saying make it a cname pointing to a TXT record?

So as an example, currently I have 

_acme-challenge.video.alliedmech.com. 599 IN TXT "FpshqKgB2q_4CSZeKJupMdaoj1klBVm_ajZaoiN2jiU"

So it sounds like you are saying make it a CNAME and have a TXT record also?

I am using (sadly) hostgator as my DNS

**Comment by siilike** [comment]
There's your problem. With this plugin certbot works as a DNS server that only replies to the _acme-challenge queries with the currently relevant TXT record.

All domains that you want to get certificates for need to have a CNAME record that points to that nameserver. No TXT or other records need to be created. Where those domains' DNS are located is not really relevant, because all requests are handled by certbot at 1.2.3.4.

So, if your certbot runs at 1.2.3.4, you need to point all _acme-challenge queries to that IP address. For that you need to define a subdomain and make 1.2.3.4 its nameserver.

First, you need to set up the nameserver part. For example, if you want to use `acme.alliedmech.com` as the nameserver subdomain, you need to define two DNS records:

  1. a NS record for `acme.alliedmech.com` that points to `ns-acme.alliedmech.com`
  2. an A record for `ns-acme.alliedmech.com` that points to 1.2.3.4 (the IP where certbot runs)

This means that when someone queries `*.acme.alliedmech.com` those requests will be handled by the nameserver at `ns-acme.alliedmech.com`, and the second rule says that `ns-acme.alliedmech.com` is at 1.2.3.4.

Next, you need to define the CNAME record for the actual domain you want to get the certificate for. In case of `alliedmech.com` it would mean that `_acme-challenge.alliedmech.com` should be a CNAME record to `alliedmech.com.acme.alliedmech.com`. In case of `example.net` it would be `_acme-challenge.example.net` -> `example.net.acme.alliedmech.com`, etc.

Finally, you need to set up and run certbot at 1.2.3.4. All _acme-challenge queries will be redirected there and the DNS records of the original domains do not have to be modified at all. Note that you cannot run an external-facing DNS server at 1.2.3.4 (but any other IPs of the same server are fine), because certbot needs to use port 53 to reply to the queries.
